network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf
kube_dashboard_path: /tmp/kubernetes-dashboard.yml

kube_version: 1.15.1

pod_network_cidr: "172.0.0.0/19"
apiserver_address: "{{ groups['kube-master'][0] | map('extract', hostvars, ['ansible_host']) }}"
calico_ipv4_pool_cidr: "172.0.0.0/19"

vagrant: False