token: b0f7b8.8d1767876297d85c
pod_network_cidr: "10.244.0.0/16"
apiserver_address: "192.168.50.10"
kubeadmin_config: /etc/kubernetes/admin.conf
kubedashboard_path: https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml