- hosts: kube-nodes
  become: yes
  tasks:
    - name: Generate kubeadm join token
      shell: kubeadm token create --print-join-command
      register: kubeadm_join_cmd
      delegate_to: "{{ groups['kube-master'][0] }}"
      run_once: yes

    - name: Run join cmd
      shell: "{{ kubeadm_join_cmd.stdout }}"