- name: Get Istio release
  unarchive:
    src: "{{ istio_release_path }}"
    dest: /tmp
    remote_src: yes

- name: Create Istio namespace
  become: yes
  become_user: "{{ kubeadm_user }}"
  shell: kubectl create namespace istio-system

#- name: Install Istio CRDs
#  become: yes
#  become_user: "{{ kubeadm_user }}"
#  shell: helm install install/kubernetes/helm/istio-init --name istio-init --namespace istio-system
#
#- name: Select default configuration profile
#  become: yes
#  become_user: vagrant
#  shell: helm install install/kubernetes/helm/istio --name istio --namespace istio-system
