- name: Get Istio release
  shell: curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.2.2 sh -

- name: Create Istio namespace
  shell: kubectl create namespace istio-system

- name: Install Istio CRDs
  command: helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f -

- name: Select default configuration profile
  command: helm template install/kubernetes/helm/istio --name istio --namespace istio-system | kubectl apply -f -
