- name: Get Istio release
  unarchive:
    src: "{{ istio_release_path }}"
    dest: /tmp
    remote_src: yes

- name: Create Istio namespace
  become: yes
  become_user: "{{ kubeadm_user }}"
  shell: kubectl create namespace istio-system
  ignore_errors: yes

- name: Copy Istio values
  copy:
    src: istio-values.yml
    dest: /tmp/istio-values.yml

- name: Copy IngressGateway
  copy:
    src: http-gateway.yml
    dest: /tmp/http-gateway.yml

- name: Install Istio CRDs
  command: helm install /tmp/istio-1.2.2/install/kubernetes/helm/istio-init --name istio-init --namespace istio-system

- name: Select configuration profile
  command: helm install /tmp/istio-1.2.2/install/kubernetes/helm/istio --name istio --namespace istio-system --values /tmp/istio-values.yml
