- name: Install kubectl
  get_url:
    url: "{{ kubectl_binary_path }}"
    dest: /usr/local/bin/kubectl
    mode: 0755

- name: Init Kubernetes cluster
  shell: |
    kubeadm init --pod-network-cidr {{ pod_network_cidr }} \
                 --kubernetes-version {{ kube_version }} \
                 --apiserver-advertise-address {{ apiserver_address }}

- name: Create Kubernetes config directory
  become: yes
  become_user: "{{ kubeadm_user }}"
  file:
    path: "~/.kube"
    state: directory
    mode: 0755

- name: Copy admin.conf to user Kubernetes config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ kubeadm_user }}/.kube/config"
    remote_src: yes
    owner: "{{ kubeadm_user }}"
