- name: Install kubectl
  yum:
    name: "kubectl-{{ kube_version }}"
    state: present

- name: Init Kubernetes cluster
  shell: |
    kubeadm init --pod-network-cidr {{ pod_network_cidr }} \
                 --apiserver-advertise-address {{ apiserver_address }}

- name: Create Kubernetes config directory
  become: yes
  become_user: vagrant
  file:
    path: "~/.kube"
    state: directory
    mode: 0755

- name: Copy admin.conf to user's Kubernetes config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
