- name: Install kubectl
  yum:
    name: kubectl-1.14.0
    state: present
    allow_downgrade: yes

- name: Init Kubernetes cluster
  shell: |
    kubeadm init --pod-network-cidr {{ pod_network_cidr }} \
                 --token {{ token }} \
                 --apiserver-advertise-address {{ apiserver_address }}

- name: Create Kubernetes config directory
  file:
    path: "~/.kube"
    state: directory
    mode: 0755

- name: Copy admin.conf to user's Kubernetes config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/root/.kube/config

- name: Deploy kubernetes dashboard into cluster
  command: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
        apply -f {{ kubedashboard_path }}
  register: create_result
  until: create_result.rc == 0
  retries: 5
  delay: 2
  ignore_errors: true