- name: Install kubectl
  yum:
    name: "kubectl-{{ kube_version }}"
    state: present

- name: Init Kubernetes cluster
  shell: |
    kubeadm init --pod-network-cidr {{ pod_network_cidr }} \
                 --apiserver-advertise-address {{ apiserver_address }}

- name: Create Kubernetes config directory
  file:
    path: "~/.kube"
    state: directory
    mode: 0755

- name: Copy admin.conf to user's Kubernetes config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/root/.kube/config

- name: Copy kubernetes dashboard spec
  file:
    src: kubernetes-dashboard.yml
    dest: "{{ kube_dashboard_path }}"

- name: Deploy kubernetes dashboard into cluster
  command: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
        apply -f {{ kube_dashboard_path }}
  register: create_result
  until: create_result.rc == 0
  retries: 5
  delay: 2
  ignore_errors: true