- name: Create Kubernetes network addon directory
  file:
    path: "{{ network_dir }}"
    state: directory

- name: Copy Calico template
  template:
    src: calico.yml.j2
    dest: "{{ network_dir }}/calico.yml"

- name: Install Calico
  command: "kubectl create --kubeconfig={{ kubeadmin_config }} -f {{ network_dir }}/calico.yml"
