- name: Create nginx ingress namespace
  become: yes
  become_user: dockeradm
  shell: |
    cat <<EOF | kubectl apply -f -
    {{ lookup('file', '../files/nginx-ingress-namespace.yml') }}
    EOF
  ignore_errors: yes

- name: Deploy nginx ingress secret
  become: yes
  become_user: dockeradm
  shell: |
    cat <<EOF | kubectl apply -f -
    {{ lookup('file', '../files/nginx-ingress-tls-secret.yml') }}
    EOF

- name: Deploy nginx ingress daemonset
  become: yes
  become_user: dockeradm
  shell: |
    cat <<EOF | kubectl apply -f -
    {{ lookup('file', '../files/nginx-ingress-daemonset.yml') }}
    EOF